### PR TITLE
fix for ranks in top.php #4967

### LINKED ISSUE #4967: Fatal error in top.php - PHP 8  - wrong parameter
## Bug Description

`Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in ***\e107_handlers\e_ranks_class.php:223 Stack trace: #0 ***\top.php(182): e_ranks->getRanks(Array, true) #1 {main} thrown in ***\e107_handlers\e_ranks_class.php on line 223`

## How to Reproduce
1. Go to top.php with users and ranks and forum

Reason:
in top.php:

```
//$ldata = get_level($row['user_id'], $row['user_plugin_forum_posts'], $row['user_comments'], $row['user_chats'], $row['user_visits'], $row['user_join'], $row['user_admin'], $row['user_perms'], $pref);
$ldata = $rank->getRanks($row, (USER && $forum->isModerator(USERID)));
```

Ranks handler:

```
	/**
	 * @param $userId
	 * @param $moderator
	 * @return array|mixed
	 */
	function getRanks($userId, $moderator = false)
```

### PR DESCRIPTION
**Pull request by Jimmi08**
CLOSES #4967

### Motivation and Context
to get top.php working in PHP8
 
### Description
ID of the user is needed, but the full user array was sent

### How Has This Been Tested?
Just used, error is away, page works

### Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### CODE REVIEW

File: top.php [hunk 1]
```diff
@@ -316,4 +316,4 @@
 	}
 }
 require_once(FOOTERF);
-?>
\ No newline at end of file
+?>
```
Comment (Deltik) [inline top.php:319]: There is now an extraneous newline after the closing `?>` tag.  Please remove the `?>` entirely to prevent the possibility of unexpected HTML getting sent after the page is processed.

Comment (Deltik) [inline top.php:319]: There is now an extraneous newline after the closing `?>` tag.  Please remove the `?>` entirely to prevent the possibility of unexpected HTML getting sent after the page is processed.

**Review by Deltik — CHANGES_REQUESTED** [review]
