### PR TITLE
FAQ Notice Removal and Apostrophe Fixes #2238

### LINKED ISSUE #2238: FAQs plugin - syntax error after latest changes
Latest github. FAQs plugin.

`Parse error: syntax error, unexpected ';' in ...\e107_plugins\faqs\faqs.php on line 617`
`Parse error: syntax error, unexpected ';' in ...\e107_plugins\faqs\faqs.php on line 620`

error is related with this 
image

after replaced older lines, FAQs works.
https://github.com/e107inc/e107/commit/340e2ed73260b323b2d858b76477a5601d2b6bf1

### PR DESCRIPTION
**Pull request by MikeyGMT**
FAQ Notice Removal and Apostrophe Fixes #2238

### CODE REVIEW

File: e107_plugins/faqs/faqs.php [hunk 1]
```diff
@@ -122,7 +122,7 @@
 
 	$faqpref = e107::getPlugConfig('faqs')->getPref();
 
-	if ($action == "" || $action == "main")
+	if (varset($action) == "" || $action == "main")
 	{
```
Comment (CaMer0n) [inline e107_plugins/faqs/faqs.php]: better way is `if(empty($action) || $action === 'main')`

Comment (MikeyGMT) [inline e107_plugins/faqs/faqs.php]: OK. Will correct it.

**Comment by CaMer0n** [comment]
Thank you!
